version: "3.8"

services:
  gemini-fastapi:
    image: gemini-fast-api
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    runtime: nvidia
    stdin_open: true   # equivalent to -i
    tty: true          # equivalent to -t
    volumes:
      - .:/gabm
    working_dir: /gabm
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    env_file:
    - .env
    ports:
    - "8000:8000"
    # command: 
    # - uvicorn main:app --host 0.0.0.0 --port 8000